### ISSUE TITLE
Can't find PATRIC_genome_info.csv

### ISSUE THREAD

**Issue by jodyphelan** [erolkavvas/microbial_AMR_ML#1]
Hi,

I am trying to run the jupyter notebook but I'm running into the following error:

```
IOError: [Errno 2] File ../data/PATRIC_genome_info.csv does not exist: '../data/PATRIC_genome_info.csv'
```
Is this file meant to be downloaded from another source?

Thanks,
Jody

**Comment by erolkavvas** [comment]
Hey Jody,

Nice catch! "PATRIC_genome_info.csv" should actually be "strain_information.csv". I noticed that the file actually is not utilized once in the code repository, so commenting out that line would also work (lol).

Also, thanks for making this a github issue! I wish that more people would do that instead of sending me emails.

Best,
Erol

**Comment by jodyphelan** [comment]
Ah great thanks! Really cool analysis btw!
